config/routes.rb
Rails.application.routes.draw do
  get 'search', to: 'books#search'
  get 'get_author', to: 'books#get_author'
  get 'book_info', to: 'books#book_info'
  post 'search', to: 'books#get_books'
  root to: 'books#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def search
  end

  def get_books
    client = Goodreads::Client.new(api_key: ENV['KEY'])
    param = params[:query] || search_params
    @results, @query_param = client.book_search(param, page: params[:page], key: client.api_key), param
  end

  def get_author
    client = Goodreads::Client.new(api_key: ENV['KEY'])
    author_name = params[:query].to_s.strip
    redirect_to client.find_author(author_name, key: client.api_key).author.link
  end

  def book_info
    client = Goodreads::Client.new(api_key: ENV['KEY'])
    book_id = params[:query].to_s.strip
    @results = client.get_book_info(book_id, key: client.api_key)
  end

  def author_info
  end

  private

  def search_params
    params.require(:books).permit(:query)[:query]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/book_info.js.erb
document.getElementById("book_id").onclick = function renderReviews () {
  // create a new div element 
  var newDiv = document.createElement("div"); 
  // and give it some content 
  var newContent = document.createTextNode("Hi there and greetings!"); 
  // add the text node to the newly created div
  newDiv.appendChild(newContent);  

  // add the newly created element and its content into the DOM 
  var currentDiv = document.getElementById("div1"); 
  document.body.insertBefore(newDiv, currentDiv); 
}

app/views/books/get_books.html.erb
<div class="main">
  <% @results.each do |r| %>
    <% r.results.work.each do |book| %>
      <div class="book">
        <a href="#"><%= image_tag(book.best_book.small_image_url) %></a>
        <div class="book_info">
          <p><%= link_to book.best_book.title, book_info_path(query: "#{book.best_book.id}"), remote: true, id: "book_id" %></p>
          <p>Author: <%= link_to "#{book.best_book.author.name}", get_author_path(query: "#{book.best_book.author.name}") %></p>
          <p>Average rating: <%= book.average_rating %></p>
          <p>published: <%= book.original_publication_year %></p>
        </div>
      </div>
    <% end %>
  <% end %>

  <div class="btn-group">
    <%= button_to "prev", search_path(page: "#{params[:page].to_i - 1}", query: @query_param), :disabled => (!params[:page] || params[:page].to_i <= 1 ), class: "btn btn-primary" %>
    <%= button_to "next", search_path(page: "#{!params[:page] ? params[:page].to_i + 2 : params[:page].to_i + 1}", query: @query_param),
      disabled: (@results[0].results_end.to_i == @results[0].total_results.to_i), class: "btn btn-primary" %>
  </div>
</div>

app/views/books/search.html.erb
<div class="main">
  <div class="wrap col-xs-8 col-xs-offset-2">
    <div class="box">
      <%= form_for :books, url: search_path, class: "search" do |f| %>
        <div class="form-group">
          <%= f.text_field :query, placeholder: "Type a book title...", autofocus: true, class: "form-control" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookFinder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>